name: CI/CD for AWS Lambda

on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
    types:
      - "opened"
      - "synchronize"

jobs:
  avoid_reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      
  test:
    runs-on: ubuntu-18.04
    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN}}
      TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: set no optional Dependencies
        run: yarn config set ignore-optional true
      - name: Install Dependencies
        run:  yarn install 

      - name: Run test suite
        run: yarn test

  build:
    needs: [test]
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build AWS Lambda zip package
        run: yarn build:lambda
      - name: Deploy on AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: sendSMS
          zip_file: lambda.zip

